PS1='\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '

export VISUAL=vi
export FZF_DEFAULT_COMMAND='ag -U -l ""'
# source ~/perl5/perlbrew/etc/bashrc
[ -f ~/.fzf.bash ] && source ~/.fzf.bash
