#!/usr/bin/env sh

. ~/config/local_config.sh

xbindkeys
echo dvorak > ~/.kblayout
kbtgl
# caps lock repat
xset r 66

# disable screen blacking
xset s off -dpms

# mouse acceleration
xinput --set-prop 9 'libinput Accel Speed' 0.2

feh --bg-scale $WALLPAPER
xcompmgr &

pkill -u $USER -f ^perl.*pstatus
pstatus &

exec dwm
