#!/usr/bin/env sh

. ~/config/local_config.sh

LC_CTYPE=pl_PL.UTF-8
LANG=pl_PL.UTF-8

xbindkeys
setxkbmap -layout pl,pl -variant dvp, -option caps:backspace,shift:both_capslock,grp:sclk_toggle

# caps lock repat
xset r 66

# disable screen blacking
xset s off -dpms
intel_backlight 35

feh --bg-scale ~/pix/wallpaper.jpg
xcompmgr &

pkill -u $USER -f ^perl.*pstatus
pstatus &

exec dwm
