#!/usr/bin/env perl

use strict;
use warnings;

my $arg = shift // 'I';

if ($arg eq 'I') {
	`doas ntfs-3g /dev/da1s1 /mnt/usb`;
}
elsif ($arg eq 'O') {
	`doas umount /mnt/usb`;
}
else {
	die 'invalid arg';
}


