#!/usr/bin/env perl

use v5.24;
use warnings;

die "please configure MON_CONFIG envvar"
	unless exists $ENV{MON_CONFIG};

my @config = split /;/, $ENV{MON_CONFIG};
my ($output, $base_output, $position) = @config;

my @cleanup = (
	$ENV{HOME} . '/.fehbg',
);

my $arg = shift // "I";
my $position = shift // $position;

if ($arg eq "I") {
	print `xrandr --output $output --auto --$position-of $base_output`;
}
elsif ($arg eq "C") {
	print `xrandr --output $output --auto --same-as $base_output`;
}
elsif ($arg eq "O") {
	print `xrandr --output $output --off`;
	print `xrandr --output $base_output --primary`;
}
else {
	die "please specify I, O or C";
}

`$_` for (@cleanup);
