#!/usr/bin/env perl

use v5.24;
use warnings;
use autodie;

my $command = "xinput";
my $pointer_master;
my $touchpad_slave;
my $enabled = 1;

{
	open my $output, "-|", $command;

	while (my $line = <$output>) {
		chomp $line;
		my ($id) = $line =~ /id=(\d+)/;
		if ($line =~ /master pointer/) {
			say "found master on id $id";
			$pointer_master = $id;
		}
		elsif ($line =~ /touchpad/i) {
			say "found touchpad on id $id";
			$touchpad_slave = $id;

			if ($line =~ /floating/) {
				$enabled = 0;
			}
		}
	}
}

if (defined $pointer_master && defined $touchpad_slave) {
	if ($enabled) {
		`$command float $touchpad_slave`;
	} else {
		`$command reattach $touchpad_slave $pointer_master`;
	}
} else {
	die "couldn't fetch full data from $command";
}
